### ISSUE TITLE
Error with missing handler for 'sentry.errors'

### ISSUE THREAD

**Issue by cmpitg** [mdgart/sentrylogs#21] opened 2016-08-26 14:04 UTC
Hi,

When using the latest SentryLogs version from Pip (0.2.0) with very simplistic setup as followed

```
sentrylogs --sentrydsn 'https://abc:xyz@app.getsentry.com/def'
```

I encountered this error:

```
No handlers could be found for logger "sentry.errors"
```

Nginx error log is at the default location (`/var/log/nginx/error.log`).  Errors were created intentionally:

```
2016/08/26 13:12:25 [emerg] 1659#1659: a duplicate default server for 0.0.0.0:80 in /etc/nginx/sites-enabled/foobar.conf:10
```

No errors got shot to Sentry.

After playing around with the source code and Raven's documentation[1], I discovered that the interface described in the documentation is `sentry.interfaces.message.Message`, while SentryLogs is using `sentry.interfaces.Message`[2].  Altering this value to `sentry.interfaces.message.Message` made it work again.

I guess at some point Raven changed the interface while SentryLogs still depends on the old one.  I'm not really familiar with Raven API so I don't know if it's a sensible fix, just so you know in case anyone else has the same problem.

[1] https://docs.sentry.io/on-premise/clientdev/interfaces/
[2] https://github.com/mdgart/sentrylogs/blob/97e66413059e433890a055479d34c8cf48795691/sentrylogs/helpers.py#L13

Ha-Duong

**Comment by bittner** [comment] 2017-02-21 23:41
Thanks, @cmpitg, for your report and investigating!

- It looks like it was actually commit https://github.com/getsentry/sentry/commit/ffcc64e99240a2880a2bca1cb08acb8f73345a0c on 29 Apr 2014.
- Interestingly, the [current docs](https://docs.sentry.io/clientdev/interfaces/message/) still (or again?) mentions `"sentry.interfaces.Message"`.
- Also the [raven tests for Django](https://github.com/getsentry/raven-python/blob/master/tests/contrib/django/tests.py#L138-L139) refer to `'sentry.interfaces.Message'`.

We'd probably have to clarify with Sentry whether this is a documentation issue (on their side) or an implementation issue (on our side, presumably).

BTW, I'm wondering if we should not better use [`captureMessage`](https://github.com/getsentry/raven-python/blob/master/raven/base.py#L771) instead of `capture`, really.

**Comment by bittner** [comment] 2017-07-17 06:25
@cmpitg Is this issue still valid?

**Comment by cmpitg** [comment] 2017-07-17 07:10
@bittner Oops, I didn't catch your reply. Sorry about that.

This issue occurred when I was working for my previous company. I no longer work there so I'm not sure what the situation is. I suppose we can close the issue and see if somebody encounters it again :-).

Ha-Duong

**Comment by punchagan** [comment] 2017-09-14 13:12
@bittner I'm seeing the exact same issue

**Comment by punchagan** [comment] 2017-09-14 15:25
I think I know what the problem is:

I am trying to use this client against a self-hosted sentry server, and not the hosted version.  The version of sentry we are running is slightly old, and I guess the API end-point is an older one.  

I tried installing an older version of `raven` (which I know works with our Sentry server), and I no longer see this error message.

**Comment by mdgart** [comment] 2018-11-16 20:51
closing this because I think it's resolved now

**Closed by mdgart** 2018-11-16 20:51 UTC
